
version: '3'
services:
  db:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - "/data/db:/usr/docker/crh_planilla/data/db"

  back:
    build: ./back/
    ports:
      - "2100:2100"
    links:
      - "db:DB"
    depends_on:
      - db
      
  front:
    build: ./front/
    ports:
      - "4220:4200"
    links:
    - "back:BACK"
    depends_on:
      - back
